# Generated by Django 3.1.5 on 2021-01-14 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bboard', '0002_auto_20201208_1246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rubric',
            options={'ordering': ['name'], 'verbose_name': 'Рубрику', 'verbose_name_plural': 'Рубрики'},
        ),
        migrations.AddField(
            model_name='bb',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='bboard_post', to='auth.user'),
            preserve_default=False,
        ),
    ]
