# Generated by Django 3.1.5 on 2021-01-14 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bboard', '0003_auto_20210114_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bb',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bboard_post', to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
    ]
